language: cpp

compiler:
    - gcc

sudo: required

before_install:
    - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
    - chmod 755 ./travis-tool.sh
    - ./travis-tool.sh bootstrap

install:
    - ./travis-tool.sh install_devtools
    - ./travis-tool.sh install_deps

script:
    - ./travis-tool.sh run_tests

on_failure:
  - ./travis-tool.sh dump_logs

notifications:
  recipients:
    - msuchard@gmail.com
    - schuemie@ohdsi.org
  email:
    on_success: change
    on_failure: change

# Revert to old cpp because Travis-CI log is too long and hard to read under new r
#language: r
#
#warnings_are_errors: true
#
#apt_packages:
#    - libcurl4-openssl-dev



